pipeline {
    agent any
    parameters {
        string(name: 'build_version', defaultValue: 'V1.0', description: 'Build version to use for Docker image')
    }

    environment {
        SONAR_URL = "http://localhost:9000"
        DOCKER_IMAGE = "prinal/demo-java-app:${build_version}"
        GIT_REPO_NAME = "devopsjava01"
        GIT_USER_NAME = "prinal"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/prinala68/devopsjava01.git'
            }
        }

        stage('Build and Test') {
            steps {
                bat 'cd demo-java-app && mvn clean package'
            }
        }

        stage('Static Code Analysis') {
            steps {
                withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
                    bat "cd demo-java-app && mvn sonar:sonar -Dsonar.login=%SONAR_AUTH_TOKEN% -Dsonar.host.url=%SONAR_URL%"
                }
            }
        }

		stage('Build and Push Docker Image') {
			environment {
				DOCKER_IMAGE = "prinal/demo-java-app:${build_version}"
				CREDS = credentials('dockerhub')
			}
			steps {
				script {
					sh 'cd demo-java-app && docker build -t ${DOCKER_IMAGE} .'

					sh """
						echo "${CREDS_PSW}" | docker login -u "${CREDS_USR}" --password-stdin
						docker push ${DOCKER_IMAGE}
					"""
				}
			}
		}


        stage('Update Deployment File') {
            steps {
                withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                    bat """
                        git config user.email "prinala68@gmail.com"
                        git config user.name "prinal"
                        sed -i "s/tag: .*/tag: \\"${build_version}\\"/" helm/app/values.yaml
                        git add helm/app/values.yaml
                        git commit -m "Update deployment image to version ${build_version}"
                        git push https://%GITHUB_TOKEN%@github.com/%GIT_USER_NAME%/%GIT_REPO_NAME% HEAD:main
                    """
                }
            }
        }
    }

    post {
        failure {
            echo "Pipeline failed. Check the logs above for details."
        }
        success {
            echo "Pipeline completed successfully!"
        }
    }
}
